# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diane Chen's Techie Blog

description: A Random Techie Blog implemented with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://purplediane.github.io/" # the base hostname & protocol for your site
twitter_username: pugpost
github_username:  purplediane

# Build settings
# markdown: KramdownPygments

markdown: kramdown
### pygments not supported on GitHub
#highlighter: pygments

## from http://blog.championswimmer.in/2015/10/jekyllsyntax-highlighting-in-github-favoured-markdown-codeblocks
## OOps. Pygments not supported on github Pages
# markdown: redcarpet
# highlighter: pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# permalink: /:title
excerpt_separator: ""

timezone: America/Los_Angeles
