# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diane Chen's Techie Blog

description: A Random Techie Blog implemented with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://purplediane.github.io/" # the base hostname & protocol for your site
twitter_username: purplediane88
github_username:  purplediane

# Build settings

markdown: kramdown
highlighter: rouge

### From http://simonvanderveldt.nl/github-pages-now-with-github-flavored-markdown-footnotes-and-syntax-highlighting/
### But I can't figure out how to make it use my _syntax-highlighting.scss file, so it's out for now.
# markdown: redcarpet
# redcarpet:
#   extensions:
#     - footnotes
#     - hard_wrap
#     - no_intra_emphasis
#     - autolink
#     - strikethrough
#
# highlighter: pygments
### end

# permalink: /:title
excerpt_separator: ""

timezone: America/Los_Angeles

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Diane Chen"
